[build]
  # Build from root for monorepo workspace support
  base = "."

  # Install from root (respects workspaces), then build frontend
  command = "npm install && npm run build:frontend"

  # Publish directory relative to root
  publish = "web/frontend/dist"

[build.environment]
  # Node Version
  NODE_VERSION = "20"

# Redirects für SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment Variables (optional - kannst du auch im Netlify Dashboard setzen)
# [context.production.environment]
#   VITE_SUPABASE_URL = "your-production-url"
#   VITE_SUPABASE_ANON_KEY = "your-production-key"
