[build]
  # Set base to frontend directory like it was before monorepo
  base = "web/frontend"

  # Simple build command like before
  command = "npm install && npm run build"

  # Publish directory relative to base
  publish = "dist"

[build.environment]
  # Node Version
  NODE_VERSION = "20"

# Redirects für SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment Variables (optional - kannst du auch im Netlify Dashboard setzen)
# [context.production.environment]
#   VITE_SUPABASE_URL = "your-production-url"
#   VITE_SUPABASE_ANON_KEY = "your-production-key"
