# Netlify Configuration

[build]
  # Build command
  command = "npm run build"
  
  # Publish directory (output from vite build)
  publish = "dist"
  
  # Functions directory (serverless functions)
  functions = "netlify/functions"

[build.environment]
  # Node version
  NODE_VERSION = "20"

# Redirects for SPA (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    X-XSS-Protection = "1; mode=block"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
